services:

  traefik:
    image: traefik:v3.2
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--experimental.localPlugins.stickyheader.moduleName=github.com/akierat/stickyheader"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "../:/plugins-local/src/github.com/akierat/stickyheader:ro"
  nginx:
    image: nginx:latest
    deploy:
      replicas: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=PathPrefix(`/nginx`)"
      - "traefik.http.routers.nginx.entrypoints=web"
      - "traefik.http.routers.nginx.middlewares=stickyheader@docker"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
      - "traefik.http.services.nginx.loadbalancer.sticky=true"
      - "traefik.http.services.nginx.loadbalancer.sticky.cookie.name=${cookieName}"
      - "traefik.http.services.nginx.loadbalancer.sticky.cookie.httpOnly=true"
      - "traefik.http.services.nginx.loadbalancer.sticky.cookie.secure=false"
      - "traefik.http.middlewares.stickyheader.plugin.stickyheader.cacheSize=${cacheSize}"
      - "traefik.http.middlewares.stickyheader.plugin.stickyheader.headerName=${headerName}"
      - "traefik.http.middlewares.stickyheader.plugin.stickyheader.cookieName=${cookieName}"

